apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: coconut-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "frontend"
        effect: "NoSchedule"
      containers:
      - name: frontend
        image: 528757801774.dkr.ecr.ap-northeast-2.amazonaws.com/src/frontend:latest
