# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: coconut-frontend
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      tolerations:  # 여기 추가
      - key: "dedicated"
        operator: "Equal"
        value: "frontend"
        effect: "NoSchedule"
      imagePullSecrets:
      - name: ecr-credentials
      containers:
      - name: frontend
        image: 992382629018.dkr.ecr.ap-northeast-2.amazonaws.com/castlehoo/frontend:106
        imagePullPolicy: Always
        env:
        - name: REACT_APP_API_BASE_URL
          value: "https://a33ed341a16cb4068b7a4d4074f66d3e-930484984.ap-northeast-2.elb.amazonaws.com:8080/api/v1"
