apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: LoadBalancer  # EKS에서는 AWS ALB가 자동으로 프로비저닝됨
  ports:
    - port: 80        # 서비스 포트
      targetPort: 80  # 컨테이너 포트 (nginx가 80포트에서 실행)
      protocol: TCP
  selector:
    app: frontend    # deployment.yaml의 label과 매칭
