apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: coconut-frontend  # default에서 변경
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend
